name: date_bottom_sheet_picker
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/Swan1993/Date_Bottom_SheetPicker

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  path: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.21.0
  intl: ^0.18.1